#!/usr/bin/env python3
"""Generate the committed hashmap fixture; not invoked by normal builds."""

import json
import random
import re
from pathlib import Path

BASE = Path(__file__).resolve().parents[1] / "data" / "headers"
COUNT = 512
SEED = 42
TOKEN = re.compile(r"[!#$%&'*+.^_`|~0-9A-Za-z-]+\Z")


def make_keys(source):
    keys = [line.strip() for line in source.splitlines()
            if line.strip() and not line.lstrip().startswith("#")]
    if any(not TOKEN.fullmatch(key) for key in keys):
        raise ValueError("invalid HTTP field name")
    supplied = len(keys)
    for key, copies in (("Set-Cookie", 8), ("WWW-Authenticate", 4), ("Link", 4)):
        if key not in keys:
            raise ValueError(f"missing duplicate fixture key: {key}")
        keys.extend([key] * copies)
    if len(keys) > COUNT:
        raise ValueError("header list and explicit duplicates exceed 512 pairs")
    rng = random.Random(SEED)
    used = {key.lower() for key in keys}
    synthetic = COUNT - len(keys)
    while len(keys) < COUNT:
        key = "X-" + "".join(rng.choice("abcdefghijklmnopqrstuvwxyz")
                             for _ in range(rng.randint(6, 22)))
        if key.lower() not in used:
            used.add(key.lower())
            keys.append(key)
    rng.shuffle(keys)
    return keys, supplied, synthetic


def generate(source):
    keys, supplied, synthetic = make_keys(source)
    lengths = [len(key) for key in keys]
    arrays = {
        "HEADER_KEYS": keys,
        "HEADER_HITS": keys,
        "HEADER_MISSES": ["!" + key[1:] for key in keys],
        "HEADER_CI_HITS": [key.swapcase() for key in keys],
        "HEADER_VALUES": [f"value-{i:04d}" for i in range(COUNT)],
    }
    lines = [
        "/* Generated by bench/scripts/gen_headers.py from http_headers.txt; seed 42. */",
        "#ifndef BENCH_HEADERS_512_H",
        "#define BENCH_HEADERS_512_H", "", '#include "hwire.h"', "",
        f"enum {{ HEADER_COUNT = {COUNT}, HEADER_MAX_KEY = {max(lengths)} }};",
        "",
    ]
    for name, values in arrays.items():
        width = max(map(len, values)) + 1
        lines.append(f"static const char {name}[HEADER_COUNT][{width}] = {{")
        lines.extend(f"    {json.dumps(value)}," for value in values)
        lines.extend(["};", ""])
    lines.append("static const hwire_kv_pair_t HEADER_PAIRS[HEADER_COUNT] = {")
    lines.extend(f"    {{{{{len(key)}, HEADER_KEYS[{i}]}}, "
                 f"{{10, HEADER_VALUES[{i}]}}}}," for i, key in enumerate(keys))
    lines.extend(["};", ""])
    for name, buffer in (("hits", "HEADER_HITS"), ("misses", "HEADER_MISSES"),
                         ("ci_hits", "HEADER_CI_HITS")):
        lines.append(f"static const hwire_str_t {name}[HEADER_COUNT] = {{")
        lines.extend(f"    {{{len(key)}, {buffer}[{i}]}},"
                     for i, key in enumerate(keys))
        lines.extend(["};", ""])
    lines.extend(["#endif", ""])
    stats = dict(pairs=COUNT, supplied=supplied, synthetic=synthetic,
                 duplicates=COUNT - len(set(keys)), unique_exact=len(set(keys)),
                 unique_ci=len({key.lower() for key in keys}),
                 min_length=min(lengths), max_length=max(lengths),
                 mean_length=sum(lengths) / COUNT, seed=SEED)
    return "\n".join(lines), stats


if __name__ == "__main__":
    content, stats = generate((BASE / "http_headers.txt").read_text())
    (BASE / "headers_512.h").write_text(content)
    print(json.dumps(stats, indent=2))
