/*
 * Single shared benchmark driver. Every registered parser is measured by
 * the identical loop over the shared fixtures, so the numbers are directly
 * comparable. The parser table is generated at build time by the Makefile
 * (bin/parserlist.c) from the parsers/<name>/ directories.
 *
 * Output: one line per benchmark into results/<name>.txt,
 *   <fixture>/<bytes> <samples> <iterations> <mean-ns> <stddev-ns>
 * which report.py renders as a comparison.
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

typedef int (*parser_fn_t)(const unsigned char *data, size_t len);

typedef struct {
    const char *name;
    parser_fn_t request;
    parser_fn_t response;
} parsers_t;

typedef struct {
    const char *name;
    const unsigned char *data;
    size_t len;
} fixture_t;

#define WARMUP_ITERS 20000
#define SAMPLES 10
#define ITERS 100000

static double now_ns(void)
{
    struct timespec ts;

    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec * 1e9 + (double)ts.tv_nsec;
}

static double bench_one(parser_fn_t fn, const unsigned char *data, size_t len)
{
    double t0, t1;
    int i;

    t0 = now_ns();
    for (i = 0; i < ITERS; i++) {
        fn(data, len);
    }
    t1 = now_ns();
    return (t1 - t0) / ITERS;
}

static int bench_direction(FILE *out, parser_fn_t fn, const fixture_t *fixtures,
                           size_t n, const char *parser, const char *dir)
{
    size_t f, s;

    for (f = 0; f < n; f++) {
        double samples[SAMPLES];
        double mean = 0.0, var = 0.0;

        if (fn(fixtures[f].data, fixtures[f].len) != 0) {
            fprintf(stderr, "%s: %s/%s: parse failed (sanity check)\n", parser,
                    dir, fixtures[f].name);
            return -1;
        }

        bench_one(fn, fixtures[f].data, fixtures[f].len); /* warm up */
        for (s = 0; s < SAMPLES; s++) {
            samples[s] = bench_one(fn, fixtures[f].data, fixtures[f].len);
            mean += samples[s];
        }
        mean /= SAMPLES;
        for (s = 0; s < SAMPLES; s++) {
            const double d = samples[s] - mean;

            var += d * d;
        }
        var /= SAMPLES - 1;

        fprintf(out, "%s/%zu %d %d %.3f %.3f\n", fixtures[f].name,
                fixtures[f].len, SAMPLES, ITERS, mean,
                var > 0.0 ? __builtin_sqrt(var) : 0.0);
    }
    return 0;
}

/* Direction selection: no argument = both, "request" = requests only,
 * "response" = responses only (used by `make request` / `make response`). */
int main(int argc, char *argv[])
{
    int do_requests = 1;
    int do_responses = 1;

    if (argc > 1) {
        if (strcmp(argv[1], "request") == 0) {
            do_responses = 0;
        } else if (strcmp(argv[1], "response") == 0) {
            do_requests = 0;
        } else {
            fprintf(stderr, "usage: %s [request|response]\n", argv[0]);
            return 1;
        }
    }
    /*
     * Generated by the Makefile: the parser table (adapter declarations
     * plus parsers[], from the parsers/ directories) and the fixture
     * tables (REQUESTS[]/RESPONSES[], from the messages/ headers).
     */
#include "parserlist.c"
#include "fixtures.c"
    size_t i;

    mkdir("results", 0755); /* EEXIST is fine */

    for (i = 0; i < sizeof(parsers) / sizeof(parsers[0]); i++) {
        const parsers_t *p = &parsers[i];
        char path[256];
        FILE *out;
        int rv = 0;

        snprintf(path, sizeof(path), "results/%s.txt", p->name);
        out = fopen(path, "w");
        if (out == NULL) {
            fprintf(stderr, "%s: cannot open %s\n", p->name, path);
            return 1;
        }
        if (do_requests) {
            rv |= bench_direction(out, p->request, REQUESTS,
                                  sizeof(REQUESTS) / sizeof(REQUESTS[0]),
                                  p->name, "request");
        }
        if (do_responses) {
            rv |= bench_direction(out, p->response, RESPONSES,
                                  sizeof(RESPONSES) / sizeof(RESPONSES[0]),
                                  p->name, "response");
        }
        fclose(out);
        if (rv != 0) {
            return 1;
        }
        printf("%s: done\n", p->name);
    }
    return 0;
}
